server:
  port: 10099

spring:
  datasource:
    url: jdbc:mariadb://localhost:20001/codeboard_blog
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: testdb#
  jpa:
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        hbm2ddl:
          auto: create

codeboard:
  member: http://localhost:100098/member

logging.level:
  org.hibernate:
    SQL: debug
    type: trace

