server:
  port: 10099

spring:
  datasource:
    url: jdbc:mariadb://localhost:30001/codeboard_blog
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: testdb#
  jpa:
# hibernate.ddl-auto와
# properties.hibernate.hbm2ddl.auto는
# 같은 옵션이다
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
#        hbm2ddl:
#          auto: create

codeboard:
  member: http://localhost:10098
  file:
    path: /Users/hwanghyeonsu/workspace/upload

logging.level:
  org:
    hibernate:
    SQL: debug
    type: trace
    springframework:
      security:
        web:
          FilterChainProxy: DEBUG

