server:
  port: 8080

#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    username: postgres
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#    password: test01#
spring:
  datasource:
    url: ${BLOG_DB_URL}
    driver-class-name: ${BLOG_DB_DRIVER}
    username: ${BLOG_DB_USER}
    password: ${BLOG_DB_PASSWD}

codeboard:
  member: codeboard-member.svc
  file:
    path: /upload

